name: file_utils
version: 1.0.0
description: File utils is a collection of the helper classes for file system.
homepage: https://github.com/mezoni/file_utils
environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  globbing: ^1.0.0
  path: ^1.8.0
dev_dependencies:  
  pedantic: ^1.10.0
  test: ^1.6.2
